"""Project detection and explicit contract/proposal generation."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml


def initial_contract(project_root: Path) -> dict[str, Any]:
    constraints: dict[str, Any] = {
        "diff_hygiene": {
            "kind": "command",
            "description": "Reject whitespace errors in the patch",
            "command": ["git", "diff", "--check"],
            "phases": ["change", "stop", "ci"],
            "watch": ["**/*"],
        }
    }
    pyproject = project_root / "pyproject.toml"
    if pyproject.is_file():
        uses_uv = (project_root / "uv.lock").is_file()
        venv_python = project_root / ".venv" / "bin" / "python"
        venv_pytest = project_root / ".venv" / "bin" / "pytest"
        uv = ["uv", "--cache-dir", ".constraintloop/uv-cache", "run"]
        if venv_python.is_file() and venv_pytest.is_file():
            python = [".venv/bin/python"]
            pytest = [".venv/bin/pytest"]
        else:
            python = [*uv, "python"] if uses_uv else ["python"]
            pytest = [*uv, "pytest"] if uses_uv else ["python", "-m", "pytest"]
        constraints["python_syntax"] = {
            "kind": "command",
            "command": [*python, "-m", "compileall", "-q", "."],
            "phases": ["change", "stop", "ci"],
            "watch": ["**/*.py"],
        }
        if (project_root / "tests").is_dir() or "pytest" in pyproject.read_text(
            encoding="utf-8", errors="ignore"
        ):
            constraints["tests"] = {
                "kind": "command",
                "command": [*pytest, "-q"],
                "phases": ["stop", "ci"],
                "watch": ["**/*.py", "pyproject.toml"],
                "needs": ["python_syntax"],
            }

    package_json = project_root / "package.json"
    if package_json.is_file():
        try:
            scripts = json.loads(package_json.read_text(encoding="utf-8")).get("scripts", {})
        except (OSError, json.JSONDecodeError):
            scripts = {}
        for name in ("lint", "typecheck", "test"):
            if name in scripts:
                constraint_id = f"npm_{name}"
                constraints[constraint_id] = {
                    "kind": "command",
                    "command": ["npm", "run", name],
                    "phases": ["stop", "ci"],
                    "watch": ["src/**/*", "test/**/*", "tests/**/*", "package.json"],
                }

    return {
        "version": 1,
        "settings": {
            "max_auto_retries": 2,
            "concurrency": 4,
            "evidence_output_limit": 65536,
            "hook_output_limit": 4096,
            "evaluation_bundle_limit": 102400,
        },
        "constraints": constraints,
        "evaluators": {},
    }


def write_initial_contract(project_root: Path) -> Path:
    path = project_root / "constraintloop.yml"
    path.write_text(
        "# Generated by ConstraintLoop. Every gate is explicit and reviewable.\n"
        + yaml.safe_dump(initial_contract(project_root), sort_keys=False),
        encoding="utf-8",
    )
    return path


def enhancement_proposal(project_root: Path) -> dict[str, Any]:
    suggestions: list[dict[str, Any]] = []
    if (project_root / "pyproject.toml").is_file():
        suggestions.extend(
            [
                {
                    "id": "ruff",
                    "reason": "Fast deterministic linting for Python",
                    "dependency": "ruff",
                    "constraint": {
                        "kind": "command",
                        "command": ["python", "-m", "ruff", "check", "."],
                        "phases": ["change", "stop", "ci"],
                        "watch": ["**/*.py", "pyproject.toml"],
                    },
                },
                {
                    "id": "coverage",
                    "reason": "Measure exercised lines; choose the threshold deliberately",
                    "dependency": "pytest-cov",
                    "constraint": {
                        "kind": "command",
                        "command": ["python", "-m", "pytest", "--cov", "--cov-fail-under=80"],
                        "phases": ["stop", "ci"],
                        "watch": ["**/*.py", "pyproject.toml"],
                    },
                },
                {
                    "id": "mutation",
                    "reason": "Check whether tests detect behavioral mutations",
                    "dependency": "mutmut",
                    "constraint": {
                        "kind": "command",
                        "command": ["python", "-m", "mutmut", "run"],
                        "phases": ["ci"],
                        "watch": ["**/*.py", "pyproject.toml"],
                        "timeout_seconds": 1800,
                    },
                },
            ]
        )
    if (project_root / "package.json").is_file():
        suggestions.append(
            {
                "id": "mutation",
                "reason": "Check whether tests detect behavioral mutations",
                "dependency": "@stryker-mutator/core",
                "constraint": {
                    "kind": "command",
                    "command": ["npx", "stryker", "run"],
                    "phases": ["ci"],
                    "watch": ["src/**/*", "test/**/*", "tests/**/*", "package.json"],
                    "timeout_seconds": 1800,
                },
            }
        )
    return {"schema_version": 1, "mode": "proposal_only", "suggestions": suggestions}


def authoring_proposal(project_root: Path) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "mode": "proposal_only",
        "rules": [
            "Generated tests must be reviewed before adoption.",
            "A generated test may not weaken or replace an existing required gate.",
            "Prefer behavioral assertions over implementation snapshots.",
        ],
        "candidates": [
            {
                "type": "acceptance_test",
                "status": "needs_human_specification",
                "prompt": "Describe the user-visible behavior and failure cases to encode.",
            },
            {
                "type": "mutation_survivor_test",
                "status": "needs_mutation_report",
                "prompt": (
                    "Add focused tests for surviving mutations without changing "
                    "production behavior."
                ),
            },
        ],
    }


def write_proposal(project_root: Path, name: str, payload: dict[str, Any]) -> Path:
    directory = project_root / ".constraintloop" / "proposals"
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{name}.yml"
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    return path
